---
- name: Print Postgres Version
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi!  Postgres version is:"
  - name: pg version
    shell: postgres --version
    
  - name: Set upgrade flag if Postgres is installed and not at version 10
    debug:
      msg: "{{ not psql.stdout.startswith('10') }}"


  - name: Check if Postgresql10 is installed even if service is stopped
    yum:
      list: installed
    register: postgresql_version
   
  - name: Print out Postgresql version from yum
    debug:
      msg: "{{ postgresql_version.stdout.find('postgresql96') }}"
 

