---
- name: Print Postgres Version
  hosts: all

  tasks:

  - name: Get postgresql version
    shell: yum list installed | grep postgres
    register: postgres_packages

  - name: Print psql version
    shell: psql --version
    register: psql_version

#   - name: Check to see if Postgres is installed
#     command: psql -tAc "SHOW server_version;"
#     become: True
#     become_user: postgres
#     changed_when: False
#     ignore_errors: True
#     register: psql

  - name: Check if Postgresql10 is installed even if service is stopped
    yum:
      list: installed
    register: postgresql_version
   
  - name: Print out Postgresql version from yum
    debug:
      msg: "{{ postgresql_version.stdout }}"
 
  - name: Register Postgresql Password Hashing Algorithm Used
    postgresql_query:
      db: postgres
      query: "SELECT COUNT(u.usename) FROM pg_catalog.pg_user u WHERE u.usename = 'awx';"
    become: True
    become_user: postgres
    register: pg_password_type
    
  - name: Print password type
    debug:
      msg: pg_password_type
