---
- name: Hello Tags
  hosts: all

  tasks:

  - name: Hello
    debug:
      msg: "Hey everybody!"
    tags:
    - hello


  - name: Goodbye
    debug:
      msg: "Bye bye!"
    tags:
    - goodbye
